baseURL = 'https://liaohch3.github.io/'
languageCode = 'en-us'
title = 'liaohch3 的个人博客'
theme = 'diary'
enableEmoji = true
DefaultContentLanguage = "zh"
googleAnalytics = "G-BTHTZ3RQ3M"

[params]
cloudflareToken = "cU9Z_VM-lskry80spcTKiFuOUvvnjOcFKAaUjQh7"

[[menu.main]]
url = "/posts"
name = "文章"
weight = 1

[[menu.main]]
url = "/tags"
name = "分类"
weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
